---
version: "2.1"
services:
  heimdall:
    env_file: .env
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ../containers.d/heimdall/data:/config
    ports:
      - "8091:80"
      - "8092:443"
    restart: unless-stopped
