---
version: "2.1"
services:
  jellyfin:
    env_file: .env
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin 
    privileged: true
    environment:
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=<022> #optional    
    # user: "1000:65534" # 113 is the id of the 'jellyfin' user on my host, 65534 is 'nogroup'
    # group_add:
    #   - "109" # 109 is the id of the 'render' group on my host
    volumes:
      - "../containers.d/jellyfin/data:/config"
      # - "../containers.d/jellyfn/cache:/cache"
      - "/media/local:/media"
      # - "/opt/vc/lib:/opt/vc/lib" #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      # VAAPI Devices
      - /dev/dri:/dev/dri #optional
      # - /dev/vcsm:/dev/vcsm #optional
      # - /dev/vchiq:/dev/vchiq #optional
      # - /dev/video10:/dev/video10 #optional
      # - /dev/video11:/dev/video11 #optional
      # - /dev/video12:/dev/video12 #optional
    restart: unless-stopped