version: '3.2'

services:
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:2.9.3-alpine
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes