version: "2.1"
services:
  wireguard:
    env_file: .env
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
      - TZ=${TIMEZONE}
#      - SERVERURL=wireguard.domain.com #optional
#      - SERVERPORT=51820 #optional
#      - PEERS=1 #optional
#      - PEERDNS=auto #optional
#      - INTERNAL_SUBNET=10.13.13.0 #optional
#      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ../containers.d/wireguard/data:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    network_mode: host
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped